appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: hASNJQ/ZUrUKkLVBJ+CQM6KXbuiMJ+s/ZKNyV35grqvTXuTHfiReGMsV+6ALvk15HPrmMlwOM6g8rCyQrKq0dBFlgZu6mzrYMcxUZ7AQwaPO+a94dCs/w9/iUiT0klsyKFo5HDL0XSadW2yWYEk2ETLpMDhS8NI1DvBw/kpbsnL8fs6XUTDtJ2jG05M2trveIaa/30OCl+h9GI9ASSonEeWheM1+htomPis9CFL/bQiZvErxwrzM19F3V6MW/LZuVB4tXz4w4FrWBXt4JabLuVnP9JG2NmozD4DdkQ4Ww5avkZHFeMSdIZgNU+vuTn60fjCr/URb+jdGM+g+B4YjAEhOM6CE6pwoaVGYNi3oC2yGwQTIMY4B2L4lgf1k+2lPfPdE0p8DI2KD8gWDCOQf9O6yQ7+gE2IE4pEjoSfGGYaJCLlKQNLXyNM0qjfS83iWCrRBIOW2iAsHEZfSHsihCCdFgEJPKBLyVcYRR6UHMhN7FCv36/ZsjtgOkDmtsHleedUvtNHzBnIH7ogzTQ1qs5VhK7NO9LEu9uCDpcQNmrpJVus6ISTyCAnT8HpCanV2sRh4mj37CLFTDUPS/ZxNAlLcTu0rGga9Nh53WH7SHPgx5SerzV0Gy6lG+R99FVFUQ2VER2Fpmss3dyZUZn7qQ8oCjwXfNpQCCxMogNSYf4A=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: false
